[IV 23-24] Objetivo 3
diagmatrix/maybe-better-maybe-worse pull request #18
Opened 2024-01-23 18:07 UTC by diagmatrix

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-01-24 16:32 UTC, johnwaves approved these changes
Hola! Me han mencionado para revisar tu PR.

Le he echado un vistazo y lo veo todo bien y en orden. Has expuesto los criterios de selección correctamente, has citado e indicado características de cada herramienta encontrada yjustificado tu elección, y también has actualizado el `README`. Buen trabajo! 🙌

2024-01-24 16:33 UTC, carlotiii30 requested changes
Buenas! En general creo que podrías ser más específico a la hora de elegir herramientas, es decir, dejar claros unos criterios y calificar las opciones en funciones a estos.  Además, te he dejado un comentario para que puedas aclararme.

2024-01-24 16:33 UTC, carlotiii30 commented on cmd/main.go
No entiendo la función de este trozo de código. ¿Es relevante en este objetivo?

2024-01-24 16:36 UTC, marinajcs requested changes
No está mal en general, aunque podrían afinarse un poco más los criterios 😀

2024-01-24 16:36 UTC, marinajcs commented on docs/criterios.md
> +  - Debido al tiempo de desarrollo del proyecto, se elegirán herramientas **sencillas** y que no supongan mucho esfuerzo de aprendizaje.
Deberían tenerse en cuenta criterios que sean cuantificables, apoyándose de herramientas como snyk.io para comprobar la puntuación (o salud) de cada herramienta. Además, ¿la facilidad de uso es realmente imprescindible?

2024-01-24 22:04 UTC, diagmatrix commented on cmd/main.go
Está ahí para seguir con los estándares de organización de un proyecto en [Go](https://github.com/golang-standards/project-layout).  Sí que es verdad que no tiene mucho sentido en este objetivo. Lo elimino

2024-01-24 22:10 UTC, diagmatrix commented on docs/criterios.md
> +  - Debido al tiempo de desarrollo del proyecto, se elegirán herramientas **sencillas** y que no supongan mucho esfuerzo de aprendizaje.
En este momento, me parece que sí que es un criterio necesario la facilidad de uso de las herramientas. Además, a posteriori, puede ser un factor importante a la hora de que otras personas contribuyan al proyecto.

2024-01-24 22:20 UTC, diagmatrix commented on docs/criterios.md
> +  - Debido al tiempo de desarrollo del proyecto, se elegirán herramientas **sencillas** y que no supongan mucho esfuerzo de aprendizaje.
Usaré la herramienta de Synk como ayuda para elegir las herramientas. Muchas gracias por la sugerencia

2024-01-24 23:08 UTC, diagmatrix commented
@carlotiii30 @marinajcs Cambios implementados :)

2024-01-25 06:42 UTC, carlotiii30 approved these changes
Muchas gracias por las correcciones. Lo veo listo

2024-01-25 11:54 UTC, marinajcs approved these changes
Me parece bien la justificación de los criterios con el apoyo de Snyk, lo veo listo para revisión 😃

2024-01-25 16:58 UTC, diagmatrix commented
@JJ Listo para revisión

2024-01-25 18:45 UTC, JJ requested changes
Muchas gracias a @marinajcs @carlotiii30 y @johnwaves en sus correciones y por hacerlo tan rápidamente. Me temo que tendrás que seguir mejor los comentarios de @marinajcs, y algún otro que te he comentado. Ánimo.

2024-01-25 18:45 UTC, JJ commented on docs/criterios.md
> +  - Debido al tiempo de desarrollo del proyecto, se elegirán herramientas **sencillas** y que no supongan mucho esfuerzo de aprendizaje.
Me temo que @marinajcs tiene razón; independientemente del tiempo que tengas, es esencial que pongas criterios que sean cuantificables. Just es sencillo, más que make, al menos, pero ¿más sencillo qu e mask? ¿Más que make u otra herramienta de uso común?
Aparte, debes resolver todos los comentarios que te hagan.

2024-01-25 18:45 UTC, JJ commented on docs/dependencias.md
> +Existen alternativas, pero están desactualizadas, ya que con la integración de **Go Modules** al conjunto de herramientas oficiales, se han dejado de desarrollar alternativas. Como posibles candidata
Si estás desactualizadas, que las nombres no añade mucha información, me temo.

2024-01-25 18:45 UTC, JJ commented on docs/gestor_tareas.md
> +| ***Deuda técnica***    | Make es una herramienta que suele estar instalada por defecto en las distribuciones Linux. De no estarlo, está disponible para esos sistemas casi sin dependencias (sólo a l
Esto también es poco cuantificables. Si lo que quieres decir es si añade dependencias o no (que parece que es lo que estás evaluando), también depende, porque lo que va a ser interesante no van a ser las distribuciones Linux, sino los contenedores. Y en esos no suele estar instalada.

2024-01-25 18:45 UTC, JJ commented on justfile
> +    go vet ./...
`go vet` hace bastante más que comprobar la sintaxis. Lo que se pide aquí es una opción del compilador que *solo* compruebe la sintaxis.

2024-01-31 09:39 UTC, JJ commented
Convendría que corrigieras esto a la mayor brevedad. Ánimo.

2024-01-31 17:05 UTC, diagmatrix commented on justfile
> +    go vet ./...
Arreglado

2024-01-31 17:25 UTC, diagmatrix commented
@JJ listo para revisión

2024-01-31 17:47 UTC, JJ requested changes
Estaría casi todo correcto, pero creo que tienes un pequeño error que puede venir de tu elección inicial y que no has cambiado. Esto te daría error en todos los tests siguientes.

2024-01-31 17:47 UTC, JJ commented on iv.yaml
> +  fichero: taskfile
Me temo que este no es el nombre del fichero que estás usando.

2024-01-31 17:47 UTC, JJ commented on iv.yaml
> +  orden: task
Y esta orden no se corresponde a la herramienta elegida.

2024-01-31 18:55 UTC, diagmatrix commented
> Estaría casi todo correcto, pero creo que tienes un pequeño error que puede venir de tu elección inicial y que no has cambiado. Esto te daría error en todos los tests siguientes.

Estoy bastante seguro de haber cambiado el gestor de **Just** a **Task**, y creo que viene reflejado en los archivos correspondientes

2024-01-31 18:55 UTC, diagmatrix commented on iv.yaml
> +  fichero: taskfile
¿Sí es, no?

2024-01-31 18:55 UTC, diagmatrix commented on iv.yaml
> +  orden: task
¿Creo que sí?

2024-01-31 18:56 UTC, diagmatrix commented
@JJ Listo para revisión

2024-01-31 19:09 UTC, JJ approved these changes
Lo voy a aprobar, pero corrígelo antes de la siguiente. :+1:

2024-01-31 19:09 UTC, JJ commented on iv.yaml
> +  orden: task
Ah, cierto. No sé por qué pensé que habías elegido just

2024-01-31 19:09 UTC, JJ commented on iv.yaml
> +  fichero: taskfile.yaml
De veras, dale una vueltecilla porque ese no es el fichero que está incluido en el PR (y volverá a dar error)

2024-01-31 19:11 UTC, merged

2024-02-11 19:29 UTC, JJ reviewed
Volviendo al objetivo 3, con algún comentario para considerar.

2024-02-11 19:29 UTC, JJ commented on README.md
> +just check
No entiendo muy bien por qué cambiaste `just` a `task`, pero esto deberías cambiarlo también. No entiendo muy bien como ha pasado los test sucesivos, problema mío seguramente.

2024-02-11 19:29 UTC, JJ commented on iv.yaml
> +  orden: task
Efectivamente cambiaste a just en [20c1b21](https://github.com/diagmatrix/maybe-better-maybe-worse/commit/20c1b215ce17b33a63c61ca4ed0a5c520d9d26c1), y lo justificaste con el #19, donde *no dice nada sobre el sentido que tiene o no elegirlo*.
A estas alturas, y visto lo visto en #29, no me parece que esté justificado ese cambio. Según veo [aquí](https://github.com/casey/just), tiene binarios prácticamente para todos los sistemas operativos. 
Como ventaja adicional, normalmente tenemos una regla en IV que no se debe elegir una herramienta por más de dos personas. Y ya contigo hace la 4ª. 
Como te digo, visto el PR para el objetivo 5º y que no has corregido totalmente lo escrito en este, realmente te aconsejaría muy vivamente que reconsideraras tu decisión.

2024-02-11 19:29 UTC, JJ commented on docs/gestor_tareas.md
> +| ***Desarrollo***       | Just está en desarrollo y tiene soporte. La última versión fue lanzada en diciembre de 2023 | ✓ |
¿Estás hablando de `just` o de `task`?

2024-02-11 20:44 UTC, diagmatrix commented on docs/gestor_tareas.md
> +| ***Desarrollo***       | Just está en desarrollo y tiene soporte. La última versión fue lanzada en diciembre de 2023 | ✓ |
De Task, es una errata

2024-02-11 20:48 UTC, diagmatrix commented on README.md
> +just check
Cambié porque al cambiar los criterios de elección, no podía seguir justificando el usar just, teniendo en cuenta que decidí que era importante que la herramienta fuese nativa de Go... Viendo los comentarios del objetivo 5, puedo cambiarlo si es mejor, no es mucho problemaa

2024-02-11 21:01 UTC, diagmatrix commented on iv.yaml
> +  orden: task
No sabía que era la 4ª persona. Viendo lo de los binarios, creo que efectivamente tiene más sentido utilizar just. Lo cambio. ¿Creo un nuevo issue o enlazo los cambios a los que están ya cerrados?

2024-02-12 00:15 UTC, diagmatrix commented on iv.yaml
> +  orden: task
Resuelto en [f461e2d](https://github.com/diagmatrix/maybe-better-maybe-worse/pull/29/commits/f461e2d9a21955d7a6692e163ec859a759e13dc5)

2024-02-12 00:22 UTC, diagmatrix commented on README.md
> +just check
Para el objetivo 5 estaba corregido.

2024-02-12 07:49 UTC, JJ commented on README.md
> +just check
Y te pedí que lo reconsideraras.